name: seconddatabase
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  async: ^2.12.0
  fake_async: ^1.3.2
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.5.3
  midtrans_sdk: ^1.0.0
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  fluttertoast: ^8.2.12 
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  firebase_database: ^11.3.6
  google_sign_in: ^6.3.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/