// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyhTW2g_dtHfvgVP7e3Qo-Q0lneHOoBMQ',
    appId: '1:972888565775:android:564a5a7c8a98a4a0b31b7a',
    messagingSenderId: '972888565775',
    projectId: 'gorcifut-db',
    databaseURL: 'https://gorcifut-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gorcifut-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqpaLWzebhX3FifezyuctATlZsm29HklY',
    appId: '1:972888565775:ios:4b3d5862355961a8b31b7a',
    messagingSenderId: '972888565775',
    projectId: 'gorcifut-db',
    databaseURL: 'https://gorcifut-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gorcifut-db.firebasestorage.app',
    iosBundleId: 'com.example.seconddatabase',
  );

}
